### ISSUE TITLE
Installation failure

### ISSUE THREAD

**Issue by 0xulver** [jacklund/btle.js#21]
Hey, I am trying to install btle.js for my project:
sudo npm install btle.js
-------------------------------------------------------------------------------------------------------------------------------------------
Outputs:

btle.js@0.2.1 install /home/rangubob/Documents/Code/JS/nodeble/node_modules/btle.js
> CXXFLAGS='-fpermissive -fexceptions' node-gyp rebuild

make: Entering directory '/home/rangubob/Documents/Code/JS/nodeble/node_modules/btle.js/build'
  CC(target) Release/obj.target/btle/src/btio.o
../src/btio.c:43:33: fatal error: bluetooth/bluetooth.h: No such file or directory
 #include <bluetooth/bluetooth.h>
                                 ^
compilation terminated.
btle.target.mk:100: recipe for target 'Release/obj.target/btle/src/btio.o' failed
make: *** [Release/obj.target/btle/src/btio.o] Error 1
make: Leaving directory '/home/rangubob/Documents/Code/JS/nodeble/node_modules/btle.js/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 4.10.0-33-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /home/rangubob/Documents/Code/JS/nodeble/node_modules/btle.js
gyp ERR! node -v v6.11.2
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! btle.js@0.2.1 install: `CXXFLAGS='-fpermissive -fexceptions' node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the btle.js@0.2.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/rangubob/.npm/_logs/2017-09-14T08_51_57_257Z-debug.log
-------------------------------------------------------------------------------------------------------------------------------------------
Linux version (uname -a):
Linux rangubob-omat 4.10.0-33-generic #37-Ubuntu SMP Fri Aug 11 10:55:28 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
BlueZ version (bluetoothctl --version):
5.43
npm (npm --version):
5.3.0

**Comment by nclavaud** [comment]
Looks like `libbluetooth-dev` is needed:
```
sudo apt-get install libbluetooth-dev
```
